### ISSUE TITLE
Upcoming Changes to Masque

### ISSUE THREAD

**Issue by StormFX** [Jaliborc/Bagnon-Facade#2]
First, this repo doesn't seem to match the files at Curse, so instead of linking to a forked branch, I used a gist.

In the next Alpha, Masque will support the `IconBorder` region better, in that it will hook it to prevent the game, or add-ons, from changing its texture. Having tested it in game, this requires a bit of a reversal of what's currently being done in Bagnon_Facade.

Instead of using the `IconGlow` region for the `Border`, simply pass `IconBorder` as its own region. Additionally, you'll want to set the texture for `IconGlow` to `nil` so it doesn't show up.

You should also use the second return of the `LibStub()` call to get Masque's API version and use that determine how to make the call so it's backwards-compatible. I've done everything in the gist except include the additional regions (listed in the change log).

https://gist.github.com/StormFX/f9de64de5d60197cb75451f9e81900e5

**Comment by Jaliborc** [comment]
Hi! Going over the mods and realized I never got to answer this.
I was a bit confused, cause what you describe and the gist appear to contradict each other? As in, in the gist you seem to have made some changes but then gone back on most of them?

Is what you wrote still true? Or should I just follow the gist? The current code of the mode appears to follow the latest version of the gist.

**Comment by StormFX** [comment]
I think the latest version of the gist is accurate, as I believe that I realized that just passing the `IconGlow` as the `IconBorder` to the button data caused the least amount of issues. But it's been awhile and my memory is a bit spotty. I would just leave it as-is and if there's changes to be made, I'll either post here or create a new issue, whichever you prefer.

**Comment by Jaliborc** [comment]
Ok! I'll close for now.
